let questions = [
    {
        numb:1,
        question:'第一次吃飯的地點?',
        answer:'老八',
        options:[
            "學餐",
            "一級棒",
            "彭爸",
            "老八"
        ]
    },
    {
        numb:2,
        question:'第一次在台北見面的時間?',
        answer:'2014年 寒假',
        options:[
            "2013年 暑假",
            "2014年 寒假",
            "2014年 暑假",
            "2013年 寒假"
        ]
    },
    {
        numb:3,
        question:'<img src="./img/audi.jpg" width="30%">此車是什麼品牌?',
        answer:'Audi',
        options:[
            "Benz",
            "Lexus",
            "Audi",
            "Volvo"
        ]
    },
    {
        numb:4,
        question:'哪一年一起看世大運?',
        answer:'2017',
        options:[
            "2015",
            "2016",
            "2017",
            "2018"
        ]
    },
    {
        numb:5,
        question:'<img src="./img/2015.04.jpg" width="25%">此明信片來自何時?',
        answer:'2015.04',
        options:[
            "2015.04",
            "2015.06",
            "2016.04",
            "2016.06"
        ]
    },
    {
        numb:6,
        question:'哪一間甜點尚未一起品嚐?',
        answer:'強森乳酪',
        options:[
            "窩巷",
            "強森乳酪",
            "美好年代",
            "米朗琪"
        ]
    },
    {
        numb:7,
        question:'第一次一起吃激旨燒鳥?',
        answer:'2016年 12月',
        options:[
            "2016年 11月",
            "2016年 12月",
            "2017年 12月",
            "2018年 12月"
        ]
    },
    {
        numb:8,
        question:'弟弟轉學考，在台北還見了哪位神秘友人?',
        answer:'馬',
        options:[
            "蔣泰叡",
            "詹姆士",
            "弟弟",
            "馬"
        ]
    },
    {
        numb:9,
        question:'環島時，送了什麼小禮物給我們?',
        answer:'面膜',
        options:[
            "面膜",
            "喝的",
            "零食",
            "防曬乳"
        ]
    },
    {
        numb:10,
        question: '<img src="./img/明信片.png" width="22%">此圖沒有哪個地方?',
        answer:'唐吉軻德',
        options:[
            "唐吉軻德",
            "南機場夜市",
            "捷絲旅",
            "天天利"
        ]
    },
    {
        numb:11,
        question: '<img src="./img/檸檬鬆餅.jpg" width="25%">什麼口味鬆餅?',
        answer:'檸檬冰淇淋',
        options:[
            "莓果塔冰淇淋",
            "芒果冰淇淋",
            "蜂蜜冰淇淋",
            "檸檬冰淇淋"
        ]
    },
    {
        numb:12,
        question:'2019年寢聚，密室逃脫位在哪一區?',
        answer:'松山區',
        options:[
            "松山區",
            "中山區",
            "南港區",
            "大安區"
        ]
    },
    {
        numb:13,
        question:'2021年1月，在哪裡吃飯?',
        answer:'台中',
        options:[
            "台北",
            "台中",
            "苗栗",
            "高雄"
        ]
    },
    {
        numb:14,
        question:'跟奶趙當了多久網友才見面?',
        answer:'8年',
        options:[
            "6年",
            "7年",
            "8年",
            "9年"
        ]
    },
    {
        numb:15,
        question:'2019年8月，除了成真咖啡還去哪裡?',
        answer:'審計新村',
        options:[
            "光復新村",
            "英才郵局",
            "審計新村",
            "新光三越"
        ]
    },
    {
        numb:16,
        question: '<img src="./img/名古屋.jpg" width="25%">圖中來自哪間店?',
        answer:'名古屋台所',
        options:[
            "山本漢堡排",
            "高木食堂",
            "鶴田屋",
            "名古屋台所"
        ]
    },
    {
        numb:17,
        question:'哪個離島，還沒寄過明信片給老凡?',
        answer:'蘭嶼',
        options:[
            "蘭嶼",
            "綠島",
            "馬祖",
            "澎湖"
        ]
    },
    {
        numb:18,
        question:'2021年，開房間的房號是?',
        answer:'907',
        options:[
            "915",
            "917",
            "907",
            "908"
        ]
    },
    {
        numb:19,
        question:'最常夢到的運動是?',
        answer:'游泳',
        options:[
            "跑步",
            "爬山",
            "打球",
            "游泳"
        ]
    },
    {
        numb:20,
        question:'2021年在101，準備了什麼小點心?',
        answer:'甜甜圈',
        options:[
            "麵包",
            "餅乾",
            "甜甜圈",
            "小蛋糕"
        ]
    },
    {
        numb:21,
        question:'老凡第一次說的生日日期?',
        answer:'2/30',
        options:[
            "2/29",
            "2/30",
            "2/31",
            "5/25"
        ]
    },
    {
        numb:22,
        question:'沒有一起進行過的活動?',
        answer:'爬山',
        options:[
            "逛街",
            "拍照",
            "吃飯",
            "爬山"
        ]
    },
    {
        numb:23,
        question: '<img src="./img/兄弟.jpg" width="23%">背景為哪棟建築?',
        answer:'兄弟大飯店',
        options:[
            "兄弟大飯店",
            "柯達大飯店",
            "南京復興站",
            "某商辦大樓"
        ]
    },
    {
        numb:24,
        question:'一起去過哪個市場?',
        answer:'第二市場',
        options:[
            "第一市場",
            "第二市場",
            "第三市場",
            "第五市場"
        ]
    },
    {
        numb:25,
        question:'<img src="./img/台南.jpg" width="23%">此明信片來自哪裡?',
        answer:'台南',
        options:[
            "台南",
            "綠島",
            "馬祖",
            "澎湖"
        ]
    },
    {
        numb:26,
        question:'住宿時，最容易吵醒誰，然後一起被瞪?',
        answer:'室友二',
        options:[
            "室友二",
            "室友三",
            "室友四",
            "室友五"
        ]
    },
    {
        numb:27,
        question:'目前為止，共寄出多少張明信片給老凡?',
        answer:'7張',
        options:[
            "4張",
            "5張",
            "6張",
            "7張"
        ]
    },
    {
        numb:28,
        question:'<img src="./img/澎湖.jpg" width="23%">此明信片來自哪裡?',
        answer:'澎湖',
        options:[
            "台南",
            "綠島",
            "馬祖",
            "澎湖"
        ]
    },
    {
        numb:29,
        question:'記事本裡，沒有哪種類型紀錄?',
        answer:'美妝',
        options:[
            "燒肉",
            "美妝",
            "甜點",
            "旅遊"
        ]
    },
    {
        numb:30,
        question:'2022/11/09，完成此project，老凡的心情?',
        answer:'想題目想破了頭= =',
        options:[
            "JS好煩",
            "還好啦!不會太高難度",
            "VUE都做出來了，這算什麼",
            "想題目想破了頭= ="
        ]
    },
    // 2023/04/08 更新
    {
        numb:31,
        question:'2023年，老凡送的生日賀禮?',
        answer:'綜合精美小茶食禮',
        options:[
            "阿里山故事茶",
            "吸水陶瓷杯墊",
            "會開花的茶",
            "綜合精美小茶食禮"
        ]
    },
    {
        numb:32,
        question:'2023/01/15，去了哪間店?',
        answer:'woosa洋食パンケーキ',
        options:[
            "NCIS Sushi",
            "woosa洋食パンケーキ",
            "新新生 xin xin sheng",
            "CHANTEZ Pâtisserie 穿石"
        ]
    },
    {
        numb:33,
        question:'承上題，還吃了什麼飯後甜點?',
        answer:'司康',
        options:[
            "司康",
            "可麗露",
            "馬芬",
            "鬆餅"
        ]
    },
    {
        numb:34,
        question:'承上題，去大稻埕使用什麼交通工具?',
        answer:'ubike',
        options:[
            "雙腳",
            "捷運",
            "ubike",
            "公車"
        ]
    },
    {
        numb:35,
        question:'承上題，哪樣物品當天沒有買?',
        answer:'手套',
        options:[
            "皮帶",
            "雨傘",
            "零錢包",
            "手套"
        ]
    },
    {
        numb:36,
        question: '<img src="./img/3D展.jpg" width="24%">此圖是什麼展覽?',
        answer:'DARK ART 夜光3D藝術展',
        options:[
            "PChome V1111P 大人物派對",
            "DARK ART 夜光3D藝術展",
            "幾何光影動物園",
            "e-RICH Planet 東聚特展"
        ]
    },
    {
        numb:37,
        question:'與哪一位朋友沒有見過面?',
        answer:'阿珺',
        options:[
            "亭亭",
            "老張",
            "阿珺",
            "奶趙"
        ]
    },
    {
        numb:38,
        question:'2015年，寢聚地點?',
        answer:'北澤',
        options:[
            "黃鶴洞",
            "北澤",
            "乾杯",
            "兩餐"
        ]
    },
    {
        numb:39,
        question:'第一屆粉絲見面會時間?',
        answer:'2021/12/03',
        options:[
            "2021/12/01",
            "2021/12/02",
            "2021/12/03",
            "2021/12/04"
        ]
    },
    {
        numb:40,
        question:'2022年，送給老凡的生日賀禮?',
        answer:'花鳥川',
        options:[
            "短腿阿鹿",
            "青鳥旅行",
            "花鳥川",
            "狸小路"
        ]
    },
    {
        numb:41,
        question:'2017/11/04，沒有去哪個地方?',
        answer:'大稻埕',
        options:[
            "齊東詩社",
            "鄭南榕紀念館",
            "大稻埕",
            "紀州庵文學森林"
        ]
    },
    {
        numb:42,
        question:'2017一起更好全民狂歡夜，在哪個連假?',
        answer:'雙十連假',
        options:[
            "清明連假",
            "中秋連假",
            "雙十連假",
            "元旦連假"
        ]
    },
    {
        numb:43,
        question:'室友們最難回答宿舍阿姨的問題?',
        answer:'柏君幾點回來',
        options:[
            "柏君幾點回來",
            "柏君在嗎",
            "我要找柏君",
            "柏君怎麼又不在"
        ]
    },
    {
        numb:44,
        question:'一起吃了哪間屋馬?',
        answer:'屋馬-文心店',
        options:[
            "屋馬-文心店",
            "屋馬-中港店",
            "屋馬-國安店",
            "屋馬-園邸店"
        ]
    },
    {
        numb:45,
        question:'2021/11/11，點了什麼飲料給老凡驚喜?',
        answer:'紅茶拿鐵',
        options:[
            "甘蔗青茶",
            "珍珠鮮奶",
            "四季春",
            "紅茶拿鐵"
        ]
    },
    {
        numb:46,
        question:'"粉絲Forever"影片中，柏拉圖曾說?',
        answer:'女人的自然本質有......',
        options:[
            "女人的珍貴青春......",
            "女人的自然本質有......",
            "女人的堅強來自於......",
            "女人的溫柔為所愛......"
        ]
    },
    {
        numb:47,
        question:'「快樂很簡單，但要簡單卻很難?」，出於誰?',
        answer:'泰戈爾',
        options:[
            "拉斐爾",
            "柏拉圖",
            "泰戈爾",
            "亞里斯多德"
        ]
    },
    {
        numb:48,
        question:'  <video src="./video/投籃.mp4" width="45%" controls autoplay> 123 ',
        answer:'進啦哪次不進',
        options:[
            "彈了出來",
            "進啦哪次不進",
            "連框都沒碰到",
            "打板界外"
        ]
    },
    {
        numb:49,
        question:'Instagram 互追紀念日?',
        answer:'2014/02/22',
        options:[
            "2014/03/22",
            "2014/02/22",
            "2014/01/22",
            "2013/12/22"
        ]
    },
        {
        numb:50,
        question: '<img src="./img/美好年代.jpg" width="24%">此甜點來自哪裡?',
        answer:'美好年代',
        options:[
            "窩巷",
            "強森乳酪",
            "美好年代",
            "米朗琪"
        ]
    },
]